src/Rest.MercuryCore.ManagementConsole/Controllers/CommonObjectCanEatDrinkController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Rest.MercuryCore.EventActions.Interface;
using Rest.MercuryCore.ManagementConsole.BLL.Loader;
using Rest.MercuryCore.ManagementConsole.Models.JsonFileObject;

namespace Rest.MercuryCore.ManagementConsole.Controllers
{
    public class CommonObjectCanEatDrinkController : Controller
    {
        private readonly ILogger<CommonObjectCanEatDrinkController> _logger;
        private readonly IActionLoader actionLoader;

        public CommonObjectCanEatDrinkController (ILogger<CommonObjectCanEatDrinkController> logger, IActionLoader actionLoader)
        {
            _logger = logger;
            this.actionLoader = actionLoader;
        }

        public IActionResult _Output (string type)
        {
            var LoadObjName = $"Load{type}";
            ILoadCommonObject comObj;
            switch (LoadObjName)
            {
                case "LoadCanEat":
                    comObj = new LoadCanEat ();
                    break;
                case "LoadCanDrink":
                    comObj = new LoadCanDrink ();
                    break;
                case "LoadCanWear":
                    comObj = new LoadCanWear ();
                    break;
                default:
                    comObj = new LoadSpecialObj ();
                    break;
            }
            comObj.OutPutFilesAsync ().Wait ();
            return Ok ("OK");
        }

        ////////////////////////////////////////////////////////////////
        public IActionResult CanEatFiles (bool reload = false)
        {
            var loadobject = new LoadCanEat ();
            return View (loadobject.GetCommonObjectModelALL (reload));
        }

        public IActionResult CanEatList (string key)
        {
            ViewBag.Key = key;
            var loadobject = new LoadCanEat ();
            return View (loadobject.GetCommonObjectModelList (key));
        }

        public IActionResult CanEatDetail (string key, string systemcode)
        {
            ViewBag.Key = key;
            ViewBag.Systemcode = systemcode;
            var loadobject = new LoadCanEat ();
            return View (loadobject.GetCommonObjectDetail (key, systemcode));
        }

        public IActionResult _CanEatSave ([FromBody] CommonObjectCanEatDrinkJsonModel para, [FromQuery] string key)
        {
            var loadobject = new LoadCanEat ();
            var result = loadobject.UpdateCommonObject (key, para);
            if (result)
                return Ok ("OK");
            else
                return StatusCode (400, "Failed");
        }
        ////////////////////////////////////////////////////////////////
        public IActionResult CanDrinkFiles (bool reload = false)
        {
            var loadobject = new LoadCanDrink ();
            return View (loadobject.GetCommonObjectModelALL (reload));
        }

        public IActionResult CanDrinkList (string key)
        {
            ViewBag.Key = key;
            var loadobject = new LoadCanDrink ();
            return View (loadobject.GetCommonObjectModelList (key));
        }
        public IActionResult CanDrinkDetail (string key, string systemcode)
        {
            ViewBag.Key = key;
            ViewBag.Systemcode = systemcode;
            var loadobject = new LoadCanDrink ();
            return View (loadobject.GetCommonObjectDetail (key, systemcode));
        }

        public IActionResult _CanDrinkSave ([FromBody] CommonObjectCanEatDrinkJsonModel para, [FromQuery] string key)
        {
            var loadobject = new LoadCanDrink ();
            var result = loadobject.UpdateCommonObject (key, para);
            if (result)
                return Ok ("OK");
            else
                return StatusCode (400, "Failed");
        }
        ////////////////////////////////////////////////////////////////
        public IActionResult CanWearFiles (bool reload = false)
        {
            var loadobject = new LoadCanWear ();
            return View (loadobject.GetCommonObjectModelALL (reload));
        }

        public IActionResult CanWearList (string key)
        {
            ViewBag.Key = key;
            var loadobject = new LoadCanWear ();
            return View (loadobject.GetCommonObjectModelList (key));
        }
        public IActionResult CanWearDetail (string key, string systemcode)
        {
            ViewBag.Key = key;
            ViewBag.Systemcode = systemcode;
            var loadobject = new LoadCanWear ();
            return View (loadobject.GetCommonObjectDetail (key, systemcode));
        }
        public IActionResult _CanWearSave ([FromBody] CommonObjectCanWearJsonModel para, [FromQuery] string key)
        {
            var loadobject = new LoadCanWear ();
            var result = loadobject.UpdateCommonObject (key, para);
            if (result)
                return Ok ("OK");
            else
                return StatusCode (400, "Failed");
        }
        ////////////////////////////////////////////////////////////////
        public IActionResult SpecialObjFiles (bool reload = false)
        {
            var loadobject = new LoadSpecialObj ();
            return View (loadobject.GetCommonObjectModelALL (reload));
        }

        public IActionResult SpecialObjList (string key)
        {
            ViewBag.Key = key;
            var loadobject = new LoadSpecialObj ();
            return View (loadobject.GetCommonObjectModelList (key));
        }
        public IActionResult SpecialObjDetail (string key, string systemcode)
        {
            ViewBag.Key = key;
            ViewBag.Systemcode = systemcode;
            var loadobject = new LoadSpecialObj ();
            return View (loadobject.GetCommonObjectDetail (key, systemcode));
        }
        public IActionResult _SpecialObjSave ([FromBody] CommonObjectSpecialJsonModel para, [FromQuery] string key)
        {
            var loadobject = new LoadSpecialObj ();
            var result = loadobject.UpdateCommonObject (key, para);
            if (result)
                return Ok ("OK");
            else
                return StatusCode (400, "Failed");
        }
    }
}

src/Rest.MercuryCore.ManagementConsole/Controllers/MobDefinationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Rest.MercuryCore.EventActions.Interface;
using Rest.MercuryCore.ManagementConsole.BLL.Loader;
using Rest.MercuryCore.ManagementConsole.Models.JsonFileObject;
using Rest.MercuryCore.ManagementConsole.Views.Models;

namespace Rest.MercuryCore.ManagementConsole.Controllers
{
    public class MobDefinationController : Controller
    {
        private readonly ILogger<MobDefinationController> _logger;
        private readonly IActionLoader actionLoader;

        public MobDefinationController (ILogger<MobDefinationController> logger, IActionLoader actionLoader)
        {
            _logger = logger;
            this.actionLoader = actionLoader;
        }

        public IActionResult FirstLayer (bool reload = false)
        {
            var loadobject = new LoadMobDefinition ();
            //Load mob locate
            new LoadMobLocateInfoModel (reload);
            return View (loadobject.GetFromFirstLayer (reload));
        }

        public IActionResult SecondLayer (string SubFolder)
        {
            ViewBag.SubFolder = SubFolder;
            var loadobject = new LoadMobDefinition ();
            return View (loadobject.GetFromSecondLayer (SubFolder));
        }

        public IActionResult ModelList (string SubFolder, string FileName)
        {
            ViewBag.SubFolder = SubFolder;
            ViewBag.FileName = FileName;
            var loadobject = new LoadMobDefinition ();
            var viewModel = loadobject.GetFromFileName (SubFolder, FileName);

            //get mob located
            var loadmoblocate = new LoadMobLocateInfoModel ();
            Dictionary<string, string> moblocate = new Dictionary<string, string> ();
            var mobNames = viewModel.Select (x => x.Name).ToList ();
            moblocate = loadmoblocate.GetSumByNames (mobNames);
            ViewBag.MobLocate = moblocate;

            return View (viewModel);
        }

        public IActionResult ModelDetail (string SubFolder, string FileName, string Name)
        {
            ViewBag.SubFolder = SubFolder;
            ViewBag.FileName = FileName;
            ViewBag.AllMobActions = actionLoader.GetAllMobAction ().Select (x => x.Key).ToList ();
            var loadobject = new LoadMobDefinition ();
            var model = loadobject.GetByName (Name);
            if (string.IsNullOrWhiteSpace (model.Name))
            {
                model = new CreatureDefinationBasicJsonModel ();
            }
            return View (model);
        }

        public IActionResult _Save ([FromBody] CreatureDefinationBasicJsonModel para, [FromQuery] string SubFolder, [FromQuery] string FileName, [FromQuery] string Name)
        {
            var loadobject = new LoadMobDefinition ();
            if (para.ViewQuestScript != null && para.ViewQuestScript.Count () > 0)
            {
                para.QuestScript = para.ViewQuestScript.ToDictionary (x => x.Key, x => x.Value);
            }
            para.ViewQuestScript = null;
            loadobject.Update (Name, SubFolder, FileName, para);
            return Ok ("OK");
        }
        public IActionResult _Output ()
        {
            var obj = new LoadMobDefinition ();
            obj.OutPutFilesAsync ().Wait ();
            return Ok ("OK");
        }

    }
}

src/Rest.MercuryCore.ManagementConsole/Controllers/RoomController.cs
using System;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Rest.MercuryCore.ManagementConsole.BLL.Loader;
using Rest.MercuryCore.ManagementConsole.Models;
using Rest.MercuryCore.Objectivate;
using Rest.MercuryCore.Utilities;
using static Rest.MercuryCore.Loader.LoadRooms.LoadRoom;

namespace Rest.MercuryCore.ManagementConsole.Controllers
{
    public class RoomController : Controller
    {
        private readonly ILogger<RoomController> _logger;

        public RoomController (ILogger<RoomController> logger)
        {
            _logger = logger;
        }

        public IActionResult RoomParentList (bool reload = false)
        {
            var loadRoomModel = new LoadRoomModel ();
            return View (loadRoomModel.GetRoomModelList (reload));
        }

        public IActionResult RoomFileList (string key)
        {
            var loadRoomModel = new LoadRoomModel ();
            ViewBag.RoomDataKey = key;
            return View (loadRoomModel.GetRoomModelList (key));
        }

        public IActionResult RoomList (string key, string subkey)
        {
            var loadRoomModel = new LoadRoomModel ();
            ViewBag.RoomDataKey = key;
            ViewBag.RoomSubDataKey = subkey;
            return View (loadRoomModel.GetRoomModelList (key, subkey));
        }

        public IActionResult RoomDetail (string key, string subkey, int id)
        {
            var loadRoomModel = new LoadRoomModel ();
            ViewBag.RoomDataKey = key;
            ViewBag.RoomSubDataKey = subkey;

            RoomDetailViewModel model = new RoomDetailViewModel ();
            model.fileRoomJsonModel = loadRoomModel.GetRoomModelList (key, subkey);
            model.roomModel = loadRoomModel.GetRoomModelList (key, subkey, id);
            if (model.roomModel == null)
            {
                model.roomModel = new RoomModel ();
            }
            return View (model);
        }

        public IActionResult NewRoomDetail (string key, string subkey, int fromRoomID, string dimensionFrom)
        {
            var loadRoomModel = new LoadRoomModel ();
            ViewBag.RoomDataKey = key;
            ViewBag.RoomSubDataKey = subkey;
            ViewBag.isNew = true;

            RoomDetailViewModel model = new RoomDetailViewModel ();
            model.fileRoomJsonModel = loadRoomModel.GetRoomModelList (key, subkey);

            //Get from roomModel
            var fromRoomModel = loadRoomModel.GetRoomModelList (key, subkey, fromRoomID);
            model.roomModel = new RoomModel ();
            if (model.fileRoomJsonModel.Rooms != null && model.fileRoomJsonModel.Rooms.Count () > 0)
                model.roomModel.RoomID = model.fileRoomJsonModel.Rooms.Max (r => r.RoomID) + 1;
            if (!string.IsNullOrWhiteSpace (dimensionFrom))
            {
                model.roomModel.Exits = new ExitSetting[]
                {
                    new ExitSetting ()
                    {
                    RoomID = fromRoomID,
                    Dimension = Enum.Parse<ExitName> (dimensionFrom).UpSideDown ()
                    }
                };
            }
            var fromRoomInfo = loadRoomModel.findRoomByRoomID (fromRoomID);
            if (fromRoomInfo.model != null)
            {
                model.roomModel.RoomTitle = fromRoomInfo.model.RoomTitle;
                model.roomModel.Description = fromRoomInfo.model.Description;
            }

            return View ("~/Views/Room/RoomDetail.cshtml", model);
        }

        public IActionResult _SaveRoomModel ([FromBody] FileRoomJsonModel para, [FromQuery] string key, [FromQuery] string subkey)
        {
            var loadRoomModel = new LoadRoomModel ();
            loadRoomModel.UpdateFileRoomJsonModel (para, key, subkey);
            return Ok ("OK");
        }

        public IActionResult _ChangeRoomID ([FromQuery] int oldRoomID, [FromQuery] int newRoomID)
        {
            var loadRoomModel = new LoadRoomModel ();
            if (loadRoomModel.ChangeRoomID (oldRoomID, newRoomID))
            {
                return Ok ("OK");
            }
            else
            {
                return StatusCode (400, "Failed");
            }
        }

        public IActionResult _ChangeExitRoomID ([FromQuery] int RoomID, [FromQuery] ExitName Dimation, [FromQuery] int newExitRoomID, [FromQuery] bool UpdateOppositeDoor)
        {
            var loadRoomModel = new LoadRoomModel ();
            if (loadRoomModel.ChangeExitRoomID (RoomID, Dimation, newExitRoomID, UpdateOppositeDoor))
            {
                return Ok ("OK");
            }
            else
            {
                return StatusCode (400, "Failed");
            }
        }

        public IActionResult _SaveRoomModelDetail ([FromBody] RoomModel para, [FromQuery] string key, [FromQuery] string subkey, [FromQuery] int RoomID, [FromQuery] bool UpdateOppositeDoor)
        {
            var loadRoomModel = new LoadRoomModel ();
            if (loadRoomModel.UpdateRoomJsonModel (para, key, subkey, RoomID, UpdateOppositeDoor))
            {
                return Ok ("OK");
            }
            else
            {
                return StatusCode (400, "Failed");
            }
        }

        public IActionResult _Output ()
        {
            var loadRoomModel = new LoadRoomModel ();
            loadRoomModel.OutPutFilesAsync ().Wait ();
            return Ok ("OK");
        }

        [ResponseCache (Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error ()
        {
            return View (new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Rest.MercuryCore.ManagementConsole/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rest.MercuryCore.ManagementConsole</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/bootstrap-multiselect.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Management Console</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Room"
                                asp-action="RoomParentList">Room Management</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MobDefination"
                                asp-action="FirstLayer">Mob defination</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownCommonObjectCanEatDrink"
                                role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Common Object
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownCommonObjectCanEatDrink">
                                <a class="dropdown-item" asp-area="" asp-controller="CommonObjectCanEatDrink"
                                    asp-action="CanEatFiles">Can Eat</a>
                                <a class="dropdown-item" asp-area="" asp-controller="CommonObjectCanEatDrink"
                                    asp-action="CanDrinkFiles">Can Drink</a>
                                <a class="dropdown-item" asp-area="" asp-controller="CommonObjectCanEatDrink"
                                    asp-action="CanWearFiles">Can Wear</a>
                                <a class="dropdown-item" asp-area="" asp-controller="CommonObjectCanEatDrink"
                                    asp-action="SpecialObjFiles">Special Object</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Rest.MercuryCore.ManagementConsole - <a asp-area="" asp-controller="Home"
                asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <a href="#" onclick="sysJs.dialog('title','message',function(){alert('aa')});return false;">Dialog sample</a>

    <div class="modal fade" id="modal-confirmation" role="dialog" aria-labelledby="dialogModelTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="dialogModelTitle">
                        Modal title
                    </h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body" id="dialogModelMessage">
                    kkkkkkkk
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" id="dialogSubmit">
                        確定
                    </button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">
                        取消
                    </button>
                </div>
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/bootstrap-multiselect.min.js" asp-append-version="false"></script>
    <script src="~/js/jquery.serializejson.min.js" asp-append-version="false"></script>
    <script src="https://cdn.tiny.cloud/1/vj5chpxgk6pzb5opo0mhjx16s2flpdnrrd234jaucqxr1h9s/tinymce/5/tinymce.min.js"
        referrerpolicy="origin"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>